var games = {
  'tloz': {
    'title': 'The Legend of Zelda',
    'category': 'Any% No Up+A',
    'offset': -1840,
    'splits': [
      '2 Toasted Corn',
      'Waldorf',
      '1 Cooler Ranch',
      '3 Nacho Cheesier',
      '4 Sweet Chili',
      'Red Drank',
      '5 Spicy Nacho',
      'Shopping Spree',
      '7 Tapatio',
      'Statler',
      '6 Salsa Verde',
      '8 Taco',
      'Best Music',
      'Zorldo',
    ],
  },

  'rollergames': {
    'title': 'Rollergames',
    'category': '',
    'offset': 0,
    'splits': [
      'Bad Attitude',
      'Mizz Georgia Hase',
      'Helicopter',
      'Maniacs',
      'John Guru Drew',
      'Truck',
      'Violators',
      'Chuck Skull',
      'Purple Maze',
      'Conveyor Belts',
      'Spike Ramps',
      'Diaper Genie',
    ],
  },

  'z2': {
    'title': 'Zelda II',
    'category': '100% All Keys',
    'offset': -2795,
    'splits': [
      'Palace 1',
      'Jump',
      'Life',
      'Hammer',
      'Medicine',
      'Fairy',
      'Palace 2',
      'Palace 3',
      'Kid',
      'Reflect',
      'Palace 4',
      'Palace 5',
      'Spell',
      'Palace 6',
      'Barrier',
      'Triforce',
    ],
  },

  'z2nmg': {
    'title': 'Zelda II',
    'category': '100% NMG',
    'offset': -2795,
    'splits': [
      'Saria',
      'Death Mountain',
      'Mido',
      'Grass Heart',
      'Palace 2',
      'Palace 3',
      'Darunia',
      'Boots',
      'Palace 5',
      'New Kasuto',
      'Palace 6',
      'Enter GP',
      'Triforce',
    ],
  },


  'z2any': {
    'title': 'Zelda II',
    'category': 'Any%',
    'offset': -2795,
    'splits': [
      'Glitch 1',
      'Hammer',
      'Errands',
      'Glitch 2',
      'Glove',
      'Wrong Warp',
      'Barrier',
      'Triforce',
    ],
  },

  'wacky': {
    'title': 'Wacky Races',
    'category': '',
    'offset': 0,
    'splits': [
        'Creepy Coupe',
      'Army Surplus Special',
      'Buzz Wagon',
      'Turbo Terrific',
      'Convert-a-Car',
      'Compact Pussycat',
      'Crimson Haybaler',
      'Bulletproof Bomb',
      'Arkansas Chugga-Bug',
      'Boulder-Mobile',
    ],
  },

  'panic': {
    'title': 'Panic Restaurant',
    'category': '',
    'offset': -1100,
    'splits': [
        'Appetizer',
      'Soup',
      'Salad',
      'Fish',
      'Meat',
      'Dessert',
    ],
  },

  'ypm': {
    'title': 'Yume Penguin Monogatari',
    'category': '',
    'offset': -2500,
    'splits': [
      'Swipe Left',
      'Pig Blimp',
      'Big Beautiful Cloud',
      'Macho Bird Raven Savage',
      'Captain Condom',
      'Swipe Right',
    ],
  },

  'tinytoons': {
    'title': 'Tiny Toons Adventures',
    'category': '',
    'offset': 0,
    'splits': [
      'Stage 1-1',
      'Stage 1-2',
      'Dragshake',
      'Stage 2-1',
      'Stage 2-2',
      'Pirate',
      'Stage 3-1',
      'Stage 3-2',
      'Plinko Bear',
      'Stage 4-1',
      'Stage 4-2',
      'Dankey Kang',
      'Collect Idiots',
      'Monty Hall',
    ],
  },

  'lttp': {
    'title': 'A Link to the Past',
    'category': 'Any% NMG',
    'offset': 0,
    'splits': [
      'Escape',
      'Eastern Palace',
      'Desert Palace',
      'Tower of Hera',
      'Agahnim\'s Tower',
      'Dark Palace',
      'Thieves\' Town',
      'Skull Woods',
      'Ice Palace',
      'Misery Mire',
      'Swamp Palace',
      'Turtle Rock',
      'Ganon\'s Tower',
      'Triforce',
    ],
  },

  'la': {
    'title': 'Link\'s Awakening',
    'category': 'Warpless',
    'offset': 0,
    'splits': [
      'Tail Key',
      'Tail Cave',
      'Power Bracelet',
      'Key Cavern',
      'Animal Warp',
      'Angler\'s Tunnel',
      'Rooster Skip Skip',
      'Eagle\'s Tower',
      'Mountain Warp',
      'Face Key',
      'Face Shrine',
      'Catfish\'s Maw',
      'Turtle Rock',
      'Bottle Grotto',
      'Windfish',
    ],
  },

  'magickingdom': {
    'title': 'Adventures in the Magic Kingdom',
    'category': 'Any%',
    'offset': -750,
    'splits': [
      'Questions',
      'No Barfing',
      'Shitty Mario Kart',
      'More Questions',
      'Claim the Dames',
      '2 Spoopy 4 Me',
      'Pause Buffer',
      'Final Questions',
    ],
  },

  'lotw': {
    'title': 'Legacy of the Wizard',
    'category': 'Any%',
    'offset': 0,
    'splits': [
      'Taratunes',
      'Erebone',
      'Archwinger',
      'Rockgaea',
      'Dragon Slayer',
    ],
  },

  'splatterhouse': {
    'title': 'Splatterhouse: Wanpaku Graffiti',
    'category': 'Any%',
    'offset': 0,
    'splits': [
      'Thriller',
      'Baby in the Corner',
      'Chicken Pot Pie',
      'Green Hamster',
      'Nightmares',
      'Racist Goat',
      'Jeff Goldblum',
      'Wario Ware',
      'Warren Zevon',
      'Stormin the Castle',
      'Screen Saver',
    ],
  },

  'gauntlet': {
    'title': 'Gauntlet (NES)',
    'category': 'Any%',
    'offset': 0,
    'splits': [
      'Castle',
      'Forest',
      'Sewer',
      'Mermaid',
      'Password',
      'Orb Get',
    ],
  },

  'anticipation': {
    'title': 'Anticipation',
    'category': 'Very Hard',
    'offset': 0,
    'splits': [
      'Claude Monet',
      'Vincent Van Gogh',
      'Pablo Picasso',
      'Bob Ross',
     ],
  },

  'yoshi': {
    'title': 'Yoshi',
    'category': 'B Type',
    'offset': 0,
    'splits': [
      'Oreo',
      'Chips Ahoy',
      'Nilla Wafer',
      'E.L. Fudge',
      'Fig Newton',
    ],
  },

  'lolo2': {
    'title': 'Adventures of Lolo 2',
    'category': 'Any%',
    'offset': 0,
    'splits': [
      'Floor 1',
      'Floor 2',
      'Floor 3',
      'Floor 4',
      'Floor 5',
      'Floor 6',
      'Floor 7',
      'Floor 8',
      'Floor 9',
      'Castle',
    ],
  },

  'ducktales': {
    'title': 'DuckTales',
    'category': 'Any%',
    'offset': -920,
    'splits': [
      'The Moon',
      'The Amazon',
      'Transylvania',
      'African Mines',
      'The Himalayas',
      'Dracula Duck',
    ],
  },

  'uninvited': {
    'title': 'Uninvited',
    'category': 'Any%',
    'offset': 0,
    'splits': [
      'Sister',
    ],
  },

  'kats': {
    'title': 'Rockin\' Kats',
    'category': 'Any%',
    'offset': 0,
    'splits': [
      'Downtown Street',
      'Western Adventure',
      'Playland',
      'Sky Ace',
      'I Love New York',
    ],
  },

  'arkista': {
    'title': 'Arkista\'s Ring',
    'category': '1st Loop',
    'offset': 0,
    'splits': [
      'Forest',
      'Sewers',
      'Mountains',
      'Tower',
      'Woods',
      'Crypt',
      'Dungeon',
      'Spiders',
      'Ninjas',
      'Ogres',
      'Stairs',
      'Boss',
    ],
  },

  'kidicarus': {
    'title': 'Kid Icarus',
    'category': 'Any%',
    'offset': -1100,
    'splits': [
      'Jump Fast',
      'Power Up',
      'More Jumping',
      'EZ Boss',
      'More Power',
      'Go Right',
      'Keep Going',
      'abs(sin(x))',
      'Up Again',
      'Up More',
      'How High',
      'Wrong Warp',
      'I\'m Finished',
    ],
  },

  'fotball': {
    'title': 'NES Play Action Football',
    'category': 'One Win',
    'offset': 0,
    'splits': [
      'Edgar Bennett',
      'Desmond Howard',
      'Reggie White',
      'Brett Favre',
    ],
  },

  'bc88': {
    'title': 'Bionic Commando',
    'category': 'Any%',
    'offset': 0,
    'splits': [
      'Coldplay',
      'Lou Bega',
      'Commodores',
      'Chicago',
      'Eiffel 65',
      'Jamiroquai',
      'Brand New',
      'Interpol',
      'Primus',
      'The Strokes',
      'Fleetwood Mac',
      'Muse',
    ],
  },

  'toki': {
    'title': 'Toki',
    'category': 'Any%',
    'offset': 0,
    'splits': [
      'Valleri',
      'I\'m a Believer',
      'Pleasant Valley Sunday',
      'Steppin\' Stone',
      'Last Train to Clarksville',
      'Daydream Believer',
    ],
  },

  'rescue': {
    'title': 'Rescue: The Embassy Mission',
    'category': 'Any%',
    'offset': 0,
    'splits': [
      'Jumbo',
      'Dick',
    ],
  },

  'faxanadu': {
    'title': 'Faxanadu',
    'category': 'Any%',
    'offset': -11300,
    'splits': [
      'Mattock',
      'Sky Spring',
      'Elixir Spring',
      'Enter Mist',
      'Three Kings',
      'Black Onyx',
      'Useless Armor',
      'Useless Sword',
      'Useless Boss',
    ],
  },

  'hh': {
    'title': 'Hammerin\' Harry',
    'category': 'Any%',
    'offset': 0,
    'splits': [
      'Stage 1',
      'Stage 2',
      'Stage 3',
      'Stage 4',
      'Stage 5',
    ],
  },

  'metalcombat': {
    'title': 'Metal Combat: Falcon\'s Revenge',
    'category': 'Any% (Falcon)',
    'offset': 0,
    'splits': [
      'Garam2',
      'Siamang',
      'Wong',
      'Griffin',
      'Viscount',
      'Thanatos',
      'Arachnus',
      'Cobra',
      'Groken',
      'Virvius',
      'Virvius 2',
      'Giga-Desp',
      'Giga-Desp 2',
    ],
  },
};
