var games = {
  'tloz': {
    'title': 'The Legend of Zelda',
    'category': 'Any% No Up+A',
    'offset': -1840,
    'splits': [
      { id: 'dorite 2', name: '2 Toasted Corn', },
      { id: 'white sword', name: 'Waldorf', },
      { id: 'dorite 1', name: '1 Cooler Ranch', },
      { id: 'dorite 3', name: '3 Nacho Cheesier', },
      { id: 'dorite 4', name: '4 Sweet Chili', },
      { id: 'red drank', name: 'Red Drank', },
      { id: 'dorite 5', name: '5 Spicy Nacho', },
      { id: 'arrows', name: 'Shopping Spree', },
      { id: 'dorite 7', name: '7 Tapatio', },
      { id: 'magic', name: 'Statler', },
      { id: 'dorite 6', name: '6 Salsa Verde', },
      { id: 'dorite 8', name: '8 Taco', },
      { id: 'entrance', name: 'Best Music', },
      { id: 'princess', name: 'Zorldo', },
    ],
  },
  'rollergames': {
    'title': 'Rollergames',
    'category': '',
    'offset': 0,
    'splits': [
      { id: 'bad attitude', name: 'Bad Attitude', },
      { id: 'mizz georgia hase', name: 'Mizz Georgia Hase', },
      { id: 'helicopter', name: 'Helicopter', },
      { id: 'maniacs', name: 'Maniacs', },
      { id: 'john guru drew', name: 'John Guru Drew', },
      { id: 'truck', name: 'Truck', },
      { id: 'violators', name: 'Violators', },
      { id: 'chuck skull', name: 'Chuck Skull', },
      { id: 'purple maze', name: 'Purple Maze', },
      { id: 'conveyor belts', name: 'Conveyor Belts', },
      { id: 'spike ramps', name: 'Spike Ramps', },
      { id: 'diaper genie', name: 'Diaper Genie', },
    ],
  },
  'z2': {
    'title': 'Zelda II',
    'category': '100% All Keys',
    'offset': -2795,
    'splits': [
      { id: 'shield', name: 'Shield', },
      { id: 'candle', name: 'Candle', },
      { id: 'palace 1', name: 'Palace 1', },
      { id: 'jump', name: 'Jump', },
      { id: 'life', name: 'Life', },
      { id: 'hammer', name: 'Hammer', },
      { id: 'medicine', name: 'Medicine', },
      { id: 'fairy', name: 'Fairy', },
      { id: 'glove', name: 'Glove', },
      { id: 'palace 2', name: 'Palace 2', },
      { id: 'raft', name: 'Wraaaaaaft', },
      { id: 'palace 3', name: 'Palace 3', },
      { id: 'fire', name: 'Fire', },
      { id: 'kid', name: 'Kid', },
      { id: 'reflect', name: 'Reflect', },
      { id: 'boots', name: 'Boots', },
      { id: 'palace 4', name: 'Palace 4', },
      { id: 'flute', name: 'Plunger', },
      { id: 'palace 5', name: 'Palace 5', },
      { id: 'spell', name: 'Spell', },
      { id: 'cross', name: 'Cross', },
      { id: 'palace 6', name: 'Palace 6', },
      { id: 'thunder', name: 'Thunder', },
      { id: 'triforce', name: 'Triforce', },
    ],
  },
  'z2-hammer': {
    'title': 'Zelda II',
    'category': 'Hammer Grab',
    'offset': -2795,
    'splits': [
      { id: 'trophy', name: 'Trophy', },
      { id: 'jump', name: 'Jump', },
      { id: 'bagu', name: 'Bagu', },
      { id: 'dm', name: 'Death Mountain', },
      { id: 'hammer', name: 'Hammer', },
    ],
  },
  'trilogy': {
    'title': 'Zelda Rando Trilogy',
    'category': '',
    'offset': 0,
    'splits': [
      { id: 'the legend', name:   'The Legend', },
      { id: 'buffer', name: 'Buffer', },
      { id: 'the adventure', name: 'The Adventure', },
      { id: 'buffer', name: 'Buffer', },
      { id: 'the past', name: 'The Past', },
    ],
  },
  'wacky': {
    'title': 'Wacky Races',
    'category': '',
    'offset': 0,
    'splits': [
      { id: 'creepy coupe', name:   'Creepy Coupe', },
      { id: 'army surplus special', name: 'Army Surplus Special', },
      { id: 'buzz wagon', name: 'Buzz Wagon', },
      { id: 'turbo terrific', name: 'Turbo Terrific', },
      { id: 'convert-a-car', name: 'Convert-a-Car', },
      { id: 'compact pussycat', name: 'Compact Pussycat', },
      { id: 'crimson haybaler', name: 'Crimson Haybaler', },
      { id: 'bulletproof bomb', name: 'Bulletproof Bomb', },
      { id: 'arkansas chugga-bug', name: 'Arkansas Chugga-Bug', },
      { id: 'boulder-mobile', name: 'Boulder-Mobile', },
    ],
  },
  'panic': {
    'title': 'Panic Restaurant',
    'category': '',
    'offset': -1100,
    'splits': [
      { id: 'appetizer', name:   'Appetizer', },
      { id: 'soup', name: 'Soup', },
      { id: 'salad', name: 'Salad', },
      { id: 'fish', name: 'Fish', },
      { id: 'meat', name: 'Meat', },
      { id: 'dessert', name: 'Dessert', },
    ],
  },
  'digger': {
    'title': 'Lil Digger',
    'category': '',
    'offset': 0,
    'splits': [
      { id: 'level 1', name: 'Level 1', },
      { id: 'fin', name: 'Fin', },
    ],
  },
  'ypm': {
    'title': 'Yume Penguin Monogatari',
    'category': '',
    'offset': -2500,
    'splits': [
      { id: 'swipe left', name: 'Swipe Left', },
      { id: 'pig blimp', name: 'Pig Blimp', },
      { id: 'big beautiful cloud', name: 'Big Beautiful Cloud', },
      { id: 'macho bird raven savage', name: 'Macho Bird Raven Savage', },
      { id: 'captain condom', name: 'Captain Condom', },
      { id: 'swipe right', name: 'Swipe Right', },
    ],
  },
  'tinytoons': {
    'title': 'Tiny Toons Adventures',
    'category': '',
    'offset': 0,
    'splits': [
      { id: 'stage 1-1', name: 'Stage 1-1', },
      { id: 'stage 1-2', name: 'Stage 1-2', },
      { id: 'dr gene splicer', name: 'Dragshake', },
      { id: 'stage 2-1', name: 'Stage 2-1', },
      { id: 'stage 2-2', name: 'Stage 2-2', },
      { id: 'pirate', name: 'Pirate', },
      { id: 'stage 3-1', name: 'Stage 3-1', },
      { id: 'stage 3-2', name: 'Stage 3-2', },
      { id: 'plinko bear', name: 'Plinko Bear', },
      { id: 'stage 4-1', name: 'Stage 4-1', },
      { id: 'stage 4-2', name: 'Stage 4-2', },
      { id: 'danky kang', name: 'Dankey Kang', },
      { id: 'collect birds', name: 'Collect Idiots', },
      { id: 'montana max', name: 'Monty Hall', },
    ],
  },
  'simonsquest': {
    'title': 'Simon\'s Quest',
    'category': 'Any%',
    'offset': -4880,
    'splits': [
      { id: 'chain', name: 'Chain Whip', },
      { id: 'heart', name: 'Dracula\'s Heart', },
      { id: 'rib', name: 'Dracula\'s Rib', },
      { id: 'eye', name: 'Dracula\'s Eye', },
      { id: 'boost', name: 'Slime Boost', },
      { id: 'ring', name: 'Dracula\'s Ring', },
      { id: 'nail', name: 'Dracula\'s Nail', },
      { id: 'dracula', name: 'Dracula', },
    ],
  },
  'smb3': {
    'title': 'Super Mario Bros 3',
    'category': 'Any% No Wrong Warp',
    'offset': 0,
    'splits': [
      { id: '1-1', name: '1-1', },
      { id: '1-2', name: '1-2', },
      { id: 'flute1', name: 'Flute 1', },
      { id: 'flute2', name: 'Flute 2', },
      { id: 'army', name: 'Army', },
      { id: 'navy', name: 'Navy', },
      { id: 'airforce', name: 'Airforce', },
      { id: '8-1', name: '8-1', },
      { id: '8-2', name: '8-2', },
      { id: '8 Fort', name: '8-fortress', },
      { id: 'Marines', name: 'marines', },
      { id: 'Princess', name: 'Princess', },
    ],
  },
  'smk': {
    'title': 'Super Mario Kart',
    'category': 'Mushroom Cup 150cc',
    'offset': 0,
    'splits': [
      { id: 'mc1', name: 'Mario Circuit 1', },
      { id: 'dp1', name: 'Donut Plains 1', },
      { id: 'gv1', name: 'Ghost Valley 1', },
      { id: 'bc1', name: 'Bowser\'s Castle 1', },
      { id: 'mc2', name: 'Mario Circuit 2', },
    ],
  },
  'smb2': {
    'title': 'Super Mario Bros. 2',
    'category': 'NES Any%',
    'offset': 0,
    'splits': [
      { id: '1-1', name: '1-1', },
      { id: '1-2', name: '1-2', },
      { id: '1-3', name: '1-3', },
      { id: '4-1', name: '4-1', },
      { id: '4-2', name: '4-2', },
      { id: '6-1', name: '6-1', },
      { id: '6-2', name: '6-2', },
      { id: '6-3', name: '6-3', },
      { id: '7-1', name: '7-1', },
      { id: '7-2', name: '7-2', },
    ],
  },
  'lttp': {
    'title': 'A Link to the Past',
    'category': 'Any% No Major Glitches',
    'offset': 0,
    'splits': [
      { id: 'escape', name: 'Escape', },
      { id: 'eastern', name: 'Eastern Palace', },
      { id: 'desert', name : 'Desert Palace', },
      { id: 'tower', name: 'Tower of Hera', },
      { id: 'agahnim', name: 'Agahnim\'s Tower', },
      { id: 'darkness', name: 'Dark Palace', },
      { id: 'thieves', name: 'Thieves\' Town', },
      { id: 'skull', name: 'Skull Woods', },
      { id: 'ice', name: 'Ice Palace', },
      { id: 'swamp', name: 'Misery Mire', },
      { id: 'misery', name: 'Swamp Palace', },
      { id: 'tutle', name: 'Turtle Rock', },
      { id: 'ganon', name: 'Ganon\'s Tower', },
      { id: 'triforce', name: 'Triforce', },
    ],
  },
  'la': {
    'title': 'Link\'s Awakening',
    'category': 'Warpless',
    'offset': 0,
    'splits': [
      { id: 'd1', name: 'Tail Cave', },
      { id: 'd3', name: 'Key Cavern', },
      { id: 'd4', name: 'Angler\'s Tunnel', },
      { id: 'd7', name: 'Eagle\'s Tower', },
      { id: 'd6', name: 'Face Shrine', },
      { id: 'd5', name: 'Catfish\'s Maw', },
      { id: 'd8', name: 'Turtle Rock', },
      { id: 'd2', name: 'Bottle Grotto', },
      { id: 'windfish', name: 'Windfish', },
    ],
  },
};
